### PR TITLE
Azure Active Directory B2C backend 

### PR DESCRIPTION
**Pull request by OmarIthawi**
Let's save the work somewhere! I'll make a dedicated repo for this backend next thing. Then will cleanup add tests and contribute the backend upstream.

Probably the dirtiest code ever, but it was pretty difficult to figure out the correct params while Microsoft provides little to no documentation about B2C.

### CODE REVIEW

**Comment by OmarIthawi** [comment]
@melvinsoft and @amirtds could you please take a look?

I'm still cleaning the code, but [`azuread_b2c.py`](https://github.com/appsembler/python-social-auth/pull/5/files#diff-041cd753b2a65f4ab5cf6832de982b10) works for now.

**Review by melvinsoft — COMMENTED** [review]
@OmarIthawi looks great so far. I'm going to save minor comments since you're still working in the code.

Just for reference, we've merged other customer backends in `appsembler/master`. You're going to push this upstream in the new social-core repo, maybe we should keep new backends in our branch, until we move to the new PSA version.

**Comment by OmarIthawi** [comment]
@amirtds and @melvinsoft the backend has been deployed and ready for review.

**Comment by OmarIthawi** [comment]
@amirtds @melvinsoft please take a look and let me know what do you think.

FYI The client is happy about the backend. It's working fine now. Let's get this merged. No need to have an additional PR dangling. If something's came up, I'll open another PR.

P.S. This is the opensource PR for your review: https://github.com/python-social-auth/social-core/pull/170.

**Comment by OmarIthawi** [comment]
I'm merging this PR. Let's save the comments for the OSPR: https://github.com/python-social-auth/social-core/pull/170

**Pull request merged**
